from selenium.webdriver.common.by import By

class AutoPageLoc:
    PHONE_TAB=(By.ID, 't-btn-tab-phone')
    PHONE_FIELD = (By.XPATH, '//span[contains(text(),"Мобильный телефон")]')
    PHONE_FIELD_ACTIV = (By.ID, 'username')
    MAIL_TAB =(By.ID,  't-btn-tab-mail')
    MAIL_FIELD = (By.XPATH, '//span[contains(text(),"Электронная почта")]')
    MAIL_FIELD_ACTIV = (By.ID, 'username')
    LOGIN_TAB = (By.ID, 't-btn-tab-login')
    LOGIN_FIELD = (By.XPATH, '//span[contains(text(),"Логин")]')
    LOGIN_FIELD_ACTIV = (By.ID, 'username')
    LS_TAB = (By.ID, 't-btn-tab-ls')
    LS_FIELD = (By.XPATH, '//span[contains(text(),"Лицевой счёт")]')
    LS_FIELD_ACTIV = (By.ID, 'username')
    PASSWORD_TAB = (By.ID, 'password')
    ENTER_TAB = (By.ID, 'kc-login')
    LK_TAB = (By.ID, 'lk-btn') # локатор для личного кабинета
    ERROR = (By.ID, 'form-error-message')
    FORGOT_PASSWORD = (By.ID, 'forgot_password')
    ERROR_MESSAGE = (By.XPATH, '//span[contains(@class, "rt-input-container__meta")]')
    REG_TAB = (By.ID, 'kc-register')
    OK_TAB = (By.XPATH, '//*[@id="oidc_ok"]')
    OK_FIELD = (By.CLASS_NAME, 'ext-widget_h_tx')
    OK_PASSWORD = (By.NAME, "fr.password")
    OK_ENTER = (By.CLASS_NAME, "button-pro __wide form-actions_yes")
    GOOGLE_TAB = (By.ID, 'oidc_google')
    GOOGLE_FIELD = (By.CLASS_NAME, 'kHn9Lb')
    GOOGLE_TAB_Next = (By.XPATH, "/html/body/div[1]/div[1]/div[2]/div/c-wiz/div/div[2]/div/div[2]/div/div[1]/div/div/button/span")
    GOOGLE_PASSWORD = (By.NAME, "password")
    ERROR_MES = (By.ID, 'form-error-message')
    ERROR_MESSAGE_EMP = (By.XPATH, '//span[contains(@class, "rt-input-container__meta")]')
    EMPRTY_PN = (By.XPATH, "//*[@id='page-right']/div/div/div/form/div[1]/div[2]/span")
    FOGPASSW_FIELD = (By.CLASS_NAME, 'card-container__title')
class RegisPage:
    REG_FIELD = (By.CLASS_NAME, 'card-container__title')
    NAME_FIELD = (By.XPATH,'//*[@id="page-right"]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/input[1]')
    SURNAME_FIELD = (By.XPATH, '//*[@id="page-right"]/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/input[1]')
    ADDRESS = (By.ID, 'address')
    PASSWORD_CONF = (By.ID, "password-confirm")
    REGIS_BUTTON = (By.XPATH, '//*[@id="page-right"]/div[1]/div[1]/div[1]/form[1]/button[1]')
    INPUT_FIELD = (By.XPATH, '//input[contains(@class, "rt-input__input")]')
    REGISTRATION_CODE_FIELD = (By.CLASS_NAME, 'card-container__title')
    ERROR_MESS = (By.XPATH, '//span[contains(@class, "rt-input-container__meta")]')
    FOGPASSW_FIELD = (By.CLASS_NAME, 'card-container__title')
    ALREADY_EXS = (By.NAME, "gotoLogin")